name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

env:
  SKIP_DEPLOYMENT_TAG: ${{ contains(github.event.head_commit.message, '#skip') || contains(join(github.event.commits.*.message, ','), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      tag_release_can_run: ${{ steps.final.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT_TAG == 'false' }}
        id: final
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Test Success Notification
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_MINE }}
          username: OnlyTest
          text: Successfully Deployed
          severity: info
          color: '#1da326'
          title: Success
          description: Testing Description. Repo ${{ github.event.repository.html_url }}
          footer: Commit by ${{ github.event.commits.committer.username}}
  tag_release:
    needs: [ simple_deployment_pipeline ]
    runs-on: ubuntu-latest
    if: ${{ needs.simple_deployment_pipeline.outputs.tag_release_can_run == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch